/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.ui;

import java.util.List;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import poly.cafe.dao.BillDAO;
import poly.cafe.dao.CardDAO;
import poly.cafe.entity.Card;
import poly.cafe.util.XImage;

/**
 *
 * @author khánh
 */
public class SalesJDialog extends javax.swing.JDialog {

    /**
     * Creates new form SalesJDialog
     */
    public SalesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    public void init() {
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        setTitle("BÁN HÀNG - THẺ KHÁCH HÀNG");
        loadCards();

        // Nếu không bọc pnlCard trong JScrollPane thì nên dùng pack() để tự chỉnh size theo nội dung
        // this.pack();
    }
    
    private void loadCards() {
        CardDAO dao = new CardDAO();
        List<Card> cards = dao.selectAll();
        pnlCard.removeAll();

        // Layout có 6 cột, các hàng tự động thêm, khoảng cách giữa các nút là 10px
        pnlCard.setLayout(new GridLayout(0, 6, 10, 10));

        for (Card card : cards) {
            pnlCard.add(createButton(card));
        }

        pnlCard.revalidate();  // Cập nhật layout
        pnlCard.repaint();     // Vẽ lại panel
    }
    
    private JButton createButton(Card card) {
        JButton btnCard = new JButton(String.format("Card #%d", card.getId()));
        btnCard.setPreferredSize(new Dimension(100, 100));
        btnCard.setEnabled(card.getStatus() == 0);  // Nếu status == 0 thì mới bật nút
        btnCard.setBackground(btnCard.isEnabled() ? Color.GREEN : Color.GRAY);

        // Gắn ID vào ActionCommand để dễ truy xuất
        btnCard.setActionCommand(String.valueOf(card.getId()));

        btnCard.addActionListener((ActionEvent e) -> {
            int cardId = Integer.parseInt(e.getActionCommand());
            //Gọi phương thức showBillDialog(int cardId) từ lớp ngoài SalesJDialog,
            //truyền vào cardId vừa lấy được.
            SalesJDialog.this.showBillJDialog(cardId);
        });

        return btnCard;
    }
    
    private void showBillJDialog(int cardId) {
        // Thực hiện hành động với cardId, ví dụ mở dialog hóa đơn
        JOptionPane.showMessageDialog(this, "Bạn đã chọn thẻ #" + cardId);

        // kiểm xem có bill chưa rồi mới mở form:

        // Mở BillManagerJDialog và truyền int cardId
        BillJDialog dialog = new BillJDialog(this, true, cardId);
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlCard.setLayout(new java.awt.GridLayout(0, 6, 5, 5));
        jScrollPane1.setViewportView(pnlCard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SalesJDialog dialog = new SalesJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCard;
    // End of variables declaration//GEN-END:variables
}
